name: Update Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install auto-changelog
        run: npm install --global auto-changelog
        working-directory: frontend

      - name: Generate CHANGELOG.md in root
        run: auto-changelog --output ../CHANGELOG.md
        working-directory: frontend

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "Update changelog"
          git push
